name: CD - Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      image_tag:
        description: 'Git SHA image tag (optional)'
        required: false

env:
  AWS_REGION: us-east-2
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply -auto-approve -var="image_uri=${{ secrets.ECR_REPOSITORY }}:${{ github.event.inputs.image_tag || github.sha }}"

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve

      - name: Trigger CodeDeploy Deployment
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          aws deploy create-deployment \
            --application-name rohana-strapi-app \
            --deployment-group-name rohana-strapi-dg \
            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
            --description "GitHub Actions Deployment - ${{ github.sha }}" \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --region $AWS_REGION

